baseURL = 'https://modbus.basjes.nl/'
languageCode = 'en-us'
title = 'Modbus Schema Toolkit'

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

[params]
# Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page.
# Useful to give opportunity to people to create merge request for your doc.
# See the config.toml file from this documentation site to have an example.
editURL = "https://github.com/nielsbasjes/modbus-website/tree/main/content/"
# Author of the site, will be used in meta information
author.name = "Niels Basjes"
# Shows a checkmark for visited pages on the menu
showVisitedLinks = false

# Change the title separator. Default to "::".
titleSeparator = " | "

disableExplicitIndexURLs = true
linkTitle = 'Modbus Schema'
collapsibleMenu = false
landingPageName = "<i class='fas fa-home'></i> Modbus Schema Toolkit"

[params.relearn.dependencies]
  [params.relearn.dependencies.math]
    name = 'Math'
  [params.relearn.dependencies.mermaid]
    name = 'Mermaid'
  [params.relearn.dependencies.openapi]
    name = 'OpenApi'

# -------------------------------------------------------------
[[menu.shortcuts]]
name = "<i class='fab fa-git-square'></i> Modbus Schema: Repo"
url = "https://github.com/nielsbasjes/modbus-schema"
weight = 10

# -------------------------------------------------------------
[[menu.shortcuts]]
name = "<i class='fab fa-git-square'></i> Device Schemas: Repo"
url = "https://github.com/nielsbasjes/modbus-devices"
weight = 20

# -------------------------------------------------------------
[[menu.shortcuts]]
name = "<i class='fab fa-git-square'></i> Sunspec: Repo"
url = "https://github.com/nielsbasjes/sunspec-device"
weight = 30

# -------------------------------------------------------------
[[menu.shortcuts]]
name = "<i class='fab fa-git-square'></i> Modbus GraphQL: Repo"
url = "https://github.com/nielsbasjes/modbus-graphql"
weight = 40

#[[menu.shortcuts]]
#name = '<img alt="License" src="https://img.shields.io/:license-apache-blue.svg"/>'
#url = "https://www.apache.org/licenses/LICENSE-2.0.html"
#weight = 40

[[menu.shortcuts]]
name = '<img alt="If this project has business value for you then dont hesitate to support me with a small donation." src="https://img.shields.io/badge/Sponsor%20me-via%20Github-darkgreen.svg" />'
url = "https://github.com/sponsors/nielsbasjes"
weight = 80
