remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: 'Modbus Schema toolkit'
description: 'A cleaner way of retrieving data from Modbus Devices'
show_downloads: false
